export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: { Row: { user_id: string; full_name: string | null; phone: string | null; avatar_url: string | null; date_of_birth: string | null; gender: string | null; blood_group: string | null; created_at: string | null; updated_at: string | null }; Insert: Partial<{ user_id: string; full_name: string | null; phone: string | null; avatar_url: string | null; date_of_birth: string | null; gender: string | null; blood_group: string | null }>; Update: Partial<{ full_name: string | null; phone: string | null; avatar_url: string | null; date_of_birth: string | null; gender: string | null; blood_group: string | null }> };
      addresses: { Row: { id: string; user_id: string; label: string; address_line1: string; address_line2: string | null; city: string; state: string; postal_code: string; country: string; latitude: number | null; longitude: number | null; is_default: boolean; created_at: string | null; updated_at: string | null }; Insert: Partial<Omit<Database['public']['Tables']['addresses']['Row'], 'id'>>; Update: Partial<Database['public']['Tables']['addresses']['Row']> };
      pharmacies: { Row: { id: string; name: string; address: string | null; latitude: number | null; longitude: number | null; rating: number | null; is_open: boolean | null; delivery_time: string | null; image_url: string | null; created_at: string | null; updated_at: string | null }; Insert: Partial<Omit<Database['public']['Tables']['pharmacies']['Row'], 'id'>>; Update: Partial<Database['public']['Tables']['pharmacies']['Row']> };
      medicine_categories: { Row: { id: string; name: string; icon: string | null; color: string | null; sort_order: number | null; is_active: boolean | null }; Insert: Partial<Database['public']['Tables']['medicine_categories']['Row']>; Update: Partial<Database['public']['Tables']['medicine_categories']['Row']> };
      medicines: { Row: { id: string; pharmacy_id: string; category_id: string | null; name: string; dosage: string | null; price: number; discounted_price: number | null; image_url: string | null; description: string | null; manufacturer: string | null; is_prescription_required: boolean | null; in_stock: boolean | null; order_count: number | null }; Insert: Partial<Omit<Database['public']['Tables']['medicines']['Row'], 'id'>>; Update: Partial<Database['public']['Tables']['medicines']['Row']> };
      cart_items: { Row: { id: string; user_id: string; medicine_id: string; quantity: number; created_at: string | null; updated_at: string | null }; Insert: Partial<Omit<Database['public']['Tables']['cart_items']['Row'], 'id'>>; Update: Partial<Database['public']['Tables']['cart_items']['Row']> };
      orders: { Row: { id: string; order_number: string | null; user_id: string; pharmacy_id: string; address_id: string; subtotal: number; delivery_fee: number; total: number; payment_method: string; status: string; created_at: string | null; updated_at: string | null }; Insert: Partial<Omit<Database['public']['Tables']['orders']['Row'], 'id'>>; Update: Partial<Database['public']['Tables']['orders']['Row']> };
      order_items: { Row: { id: string; order_id: string; medicine_id: string; medicine_name: string; quantity: number; unit_price: number; total_price: number }; Insert: Partial<Omit<Database['public']['Tables']['order_items']['Row'], 'id'>>; Update: Partial<Database['public']['Tables']['order_items']['Row']> };
      doctors: { Row: { id: string; name: string; specialty_id: string | null; photo_url: string | null; about: string | null; experience_years: number | null; consultation_fee: number | null; rating: number | null; languages: string[] | null; education: string[] | null; consultation_type: string | null }; Insert: Partial<Omit<Database['public']['Tables']['doctors']['Row'], 'id'>>; Update: Partial<Database['public']['Tables']['doctors']['Row']> };
      specialties: { Row: { id: string; name: string; icon: string | null }; Insert: Partial<Database['public']['Tables']['specialties']['Row']>; Update: Partial<Database['public']['Tables']['specialties']['Row']> };
      availability_slots: { Row: { id: string; doctor_id: string; slot_date: string; slot_time: string; is_available: boolean }; Insert: Partial<Omit<Database['public']['Tables']['availability_slots']['Row'], 'id'>>; Update: Partial<Database['public']['Tables']['availability_slots']['Row']> };
      appointments: { Row: { id: string; patient_id: string; doctor_id: string; appointment_date: string; appointment_time: string; consultation_type: string; status: string; created_at: string | null }; Insert: Partial<Omit<Database['public']['Tables']['appointments']['Row'], 'id'>>; Update: Partial<Database['public']['Tables']['appointments']['Row']> };
      notifications: { Row: { id: string; user_id: string; title: string; message: string; type: string; is_read: boolean; data: Json | null; created_at: string | null }; Insert: Partial<Omit<Database['public']['Tables']['notifications']['Row'], 'id'>>; Update: Partial<Database['public']['Tables']['notifications']['Row']> };
      emergency_requests: { Row: { id: string; user_id: string; message: string; created_at: string | null }; Insert: Partial<Omit<Database['public']['Tables']['emergency_requests']['Row'], 'id'>>; Update: Partial<Database['public']['Tables']['emergency_requests']['Row']> };
    };
  };
}
